
mkdir -p /home/ubuntu/StackWatch
cd /home/ubuntu/StackWatch

# Create docker-compose file (image-based now)
cat > docker-compose.yml <<'COMPOSEEOF'
services:
  backend:
    image: ghcr.io/jameboyyy/stackwatch-backend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/jameboyyy/stackwatch-frontend:latest
    container_name: stackwatch-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
COMPOSEEOF


docker compose pull
docker compose up -d